// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/permission/healthy.proto

package permission

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Healthy service

func NewHealthyEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Healthy service

type HealthyService interface {
	// 回显
	Echo(ctx context.Context, in *EchoRequest, opts ...client.CallOption) (*EchoResponse, error)
}

type healthyService struct {
	c    client.Client
	name string
}

func NewHealthyService(name string, c client.Client) HealthyService {
	return &healthyService{
		c:    c,
		name: name,
	}
}

func (c *healthyService) Echo(ctx context.Context, in *EchoRequest, opts ...client.CallOption) (*EchoResponse, error) {
	req := c.c.NewRequest(c.name, "Healthy.Echo", in)
	out := new(EchoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Healthy service

type HealthyHandler interface {
	// 回显
	Echo(context.Context, *EchoRequest, *EchoResponse) error
}

func RegisterHealthyHandler(s server.Server, hdlr HealthyHandler, opts ...server.HandlerOption) error {
	type healthy interface {
		Echo(ctx context.Context, in *EchoRequest, out *EchoResponse) error
	}
	type Healthy struct {
		healthy
	}
	h := &healthyHandler{hdlr}
	return s.Handle(s.NewHandler(&Healthy{h}, opts...))
}

type healthyHandler struct {
	HealthyHandler
}

func (h *healthyHandler) Echo(ctx context.Context, in *EchoRequest, out *EchoResponse) error {
	return h.HealthyHandler.Echo(ctx, in, out)
}
